namespace ArkanoidDXUniverse
{
    public class Monologue
    {
        public static string OringinalOpening =
            "THE TIME AND ERA OF THIS STORY IS UNKNOWN, AFTER THE MOTHERSHIP ARKANOID WAS DESTROYED, A SPACECRAFT VAUS SCRAMBLED AWAY FROM IT. BUT ONLY TO BE TRAPPED IN SPACE WARPED BY SOMEONE...";

        public static string OringinalEnding =
            "DIMENSION-CONTROLLING FORT Doh HAS NOW BEEN DEMOLISHED, AND TIME STARTED FLOWING REVERSELY. VAUS MANAGED T ESCAPE FROM THE DISTORTED SPACE. BUT THE REAL VOYAGE OF ARKANOID IN THE GALAXY HAS ONLY STARTED...";
    }
}